version: '2'

services:

  cwltool:
    build:
      context: .
      dockerfile: Dockerfile-dev
    working_dir: "/app/"
    environment:
      CCC: 'ccc:9000'
    # command: ["/usr/bin/nodemon", "--ext", "py", "--watch", "/root/cwltool", "--watch", "/root/bin", '--exec', '/usr/bin/python -m', 'cwltool.main', "--debug", "run_workflow.cwl", "input.yml"]
    command: ["/usr/bin/nodemon", "--ext", "py", "--watch", "/root/cwltool", "--watch", "/root/bin", '--exec', '/root/bin/download-run-workflow', "https://github.com/dionjwa/cwltool.git", "8d29aee79df64f8448d91429062fc23ec2c28f98", "tests/ccc_docker_workflow/run_workflow.cwl", "tests/ccc_docker_workflow/input.yml"]
    entrypoint: []
    volumes:
      - ./bin:/root/bin
      - ./tests/ccc_docker_workflow:/app
      # - ./cwltool:/root/cwltool
      # - ./convert_pdb_workflow_example:/app/
      # - ./5b10.pdb:/app/uploadpdb.pdb
    links:
      - ccc

  ccc:
    image: "quay.io/bionano/cloud-compute-cannon:40d654be"
    command: ["nodemon", "-w", "server", "server/cloud-compute-cannon-server.js"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ccc-local-storage:/app/ccc-local-storage
    ports:
      - "9100:9000"
    environment:
      PORT: "9000"
      HOST_PWD: "$PWD"
      STORAGE_HTTP_PREFIX: 'http://ccc:9000/'
      REDIS_HOST: 'redis1'
      LOG_LEVEL: "40"
      CLIENT_DEPLOYMENT: "false"
      SCALE_UP_CONTROL: "external"
      SCALE_DOWN_CONTROL: "external"
      ENABLE_FLUENT: "false"
      LOCAL: "true"
    links:
      - redis1

  redis1:
    image: redis:3.2.0-alpine
    # command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379"